# Generated by Django 5.1.1 on 2024-10-23 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_rename_tipo_caracteristica_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='caracteristicas',
            field=models.ManyToManyField(blank=True, to='productos.caracteristica'),
        ),
    ]
