# Generated by Django 5.1.1 on 2024-10-25 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_tipocaracteristica_remove_caracteristica_nombre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caracteristica',
            name='tipo',
        ),
        migrations.AddField(
            model_name='caracteristica',
            name='nombre',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='codigo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='marca',
            field=models.CharField(max_length=100),
        ),
    ]
