# Generated by Django 5.1.1 on 2024-10-25 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_remove_caracteristica_tipo_caracteristica_nombre_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caracteristica',
            old_name='nombre',
            new_name='caracteristica',
        ),
        migrations.RemoveField(
            model_name='caracteristica',
            name='valor',
        ),
    ]
